verbose: 2
input_data_folder: step_1/
#input_data_folder: small_set/
# TODO: not fully implemented yet only some of the random operations use this seed
random_seed: 42  # set to null for different results each time
# if project is executed inside a notebook, set this to True. It will
# - save images instead of displaying them
notebook_mode: False

# DISPLAY OPTIONS
display_confusion_matrix: True
worst_n_predictions: 10
best_n_configurations: 15

# CUSTOM MODEL CONFIGURATION
custom_model_parameters:
    num_conv_layers: 3
    dense_layers: [4096, 512, 64]
    convolution_parameters:
        in_channels: 3
        out_channels: 16
        groups: 1
        kernel_size: 3
        stride: 1
        padding: same
    pooling_operation: MaxPool2d
    pooling_parameters:
        kernel_size: 2
        stride: 2
        padding: 0
    temp_dense_layer_dimension: 7744  # temporary fix

# PRE-TRAINED MODEL CONFIGURATION
# Warning: case-sensitive names
pretrained_model_parameters:
    # REGNET MODEL
    # model_architecture: regnet
    # model_version: regnet_y_1_6gf  # small
    # weights_name: RegNet_Y_1_6GF_Weights.DEFAULT
    # model_version: regnet_y_128gf  # big
    # weights_name: RegNet_Y_128GF_Weights.DEFAULT
    # RESNET MODEL
    model_architecture: resnet
    model_version: resnet50
    weights_name: ResNet50_Weights.DEFAULT
    # CONVNEXT MODEL
    # model_architecture: convnext
    # model_version: convnext_small
    # weights_name: ConvNeXt_Small_Weights.DEFAULT
    # SWIN TRANSFORMER MODEL
    # model_architecture: swin_transformer
    # model_version: swin_t
    # weights_name: Swin_T_Weights.DEFAULT
    freeze_layers: False

# TRAINING HYPERPARAMETERS
# width and height of images
# img_dim: 95
batch_size: 16
num_epochs: 4
learning_rate: !!float 5e-5
optimizer_name: Adam
# optimizer_name: RMSprop
loss_function_name: CrossEntropyLoss
shuffle: True
save_model: True
# must add up to 1 +/- tolerance
train_val_test_proportions: [0.8, 0.1, 0.1]
tolerance: 0.01
# number of times the original dataset is duplicated with random variations
data_augmentation_proportion: 1
balance_data: False

metrics:
    Accuracy:
        task: multiclass
        average: weighted
#        average: none
    Precision:
        task: multiclass
        average: weighted
#        average: none
    Recall:
        task: multiclass
        average: weighted
#        average: none
    F1Score:
        task: multiclass
        average: weighted
#        average: none


# MODEL USAGE PARAMETERS
# use only those images, if null, use all images in folder
# img_name_list = [buna_s1_0.tif, buna_s1_1.tif]
img_name_list: null
jump: 1
use_targets: False

grid_search_parameters:
    # number of tests for each configuration, to have a more accurate estimate of the performance
    num_tests_for_configuration: 3
    # keys here should match the names of the variables in this config file with '_list' appended
    # e.g. 'augment_data_list' is the key for the list of values for the proportion of data to augment.
    # each combination of values will be tested num_tests_for_configuration times
    # and the average performance will be used to select the best configuration.
    # use lists of one element to test only one value for that variable.
    search_space:
        data_augmentation_proportion_list: [1, 4, 8]
        # data_augmentation_proportion_list: [5]
        # batch_size_list: [8, 16, 32]
        batch_size_list: [64]
        # learning_rate_list: [0.005, 0.0001]
        learning_rate_list: [!!float 1e-04, !!float 1e-05, !!float 1e-06]
        # num_epochs_list: [10, 20]
        num_epochs_list: [4]
        # optimizer_name_list: [Adam, RMSprop]
        optimizer_name_list: [Adam]
        balance_data_list: [False, True]
        # balance_data_list: [False]
        # WARNING: case-sensitive names [model_architecture, model_version, weights_name]
        model_spec_list: [
#            [regnet, regnet_y_1_6gf, RegNet_Y_1_6GF_Weights.DEFAULT],
#            [regnet, regnet_y_1_6gf, None],
#            [regnet, regnet_y_128gf, RegNet_Y_128GF_Weights.DEFAULT],
#            [swin_transformer, swin_s, Swin_S_Weights.DEFAULT],
#            [swin_transformer, swin_t, Swin_T_Weights.DEFAULT],
            [resnet, resnet50, ResNet50_Weights.DEFAULT],
            ]
        # to train a model from scratch, set weights_name to None
        # freeze_layers_list: [True, False]
        freeze_layers_list: [False]